Repository quarks-css/quarks, pull requests merged in 2023-05, with the labels that each got.

#5 feat: `quarks` types & `createStylesFromProps`
  .eslintrc
  .gitignore
  src/constants/prefix.ts
  src/constants/pseudoElements.ts
  src/createStylesFromProps.ts
  src/index.ts
  src/quark.ts
  src/setup.ts
  src/theme/customOverwrites.ts
  src/types/pseudos.ts
  src/types/quarkProps.ts
  src/utils/propChecks.ts
  src/utils/typeUtils.ts
Labels: enhancement

#46 docs: updates to README.md
  .github/dependabot.yml
  .github/workflows/pipeline.yml
  README.md
  src/assets/quarks-logo.png
  src/assets/quarks-logo.svg
Labels: documentation

#50 docs(README): switch badges to links
  README.md
Labels: documentation, needs review
